[build]
command = "npm run build"
publish = "build"
#publish = ".next"

[dev]
command = "npm run dev"  # Optional: for local development

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "development"

[context.production]
publish = "build/"
#command = "make publish"


#[context.deploy-preview]
#publish = "build/"

[build.environment]
NODE_ENV = "development"
NODE_VERSION = "16"  # Change to your preferred version

[cache]
paths = ["build/**/*", ".next/cache/**/*"]  # Specify the cache paths
